language: rust
cache: cargo
dist: xenial
sudo: true
os:
- linux
- osx
- windows

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
    - zlib1g-dev

# Run builds for all the supported trains
rust:
- 1.40.0
- 1.41.0
- 1.42.0
- 1.43.0
- 1.44.0
- stable
- beta
- nightly

stages:
- test
- deploy

# Extra jobs to include
jobs:
  include:
  # Upload documentation
  - name: "Documentation upload"
    os: linux
    rust: stable
    stage: deploy
    env: CACHE_NAME=DOCS
    script: ./travis-helper.sh documentation
    deploy: &pages
      provider: pages
      github-token: $GH_TOKEN
      local-dir: target/doc/
      skip_cleanup: true
      keep-history: true
      on:
        repo: Razican/bittrex-rs
        branch: develop
  # Crates.io deployment
  - name: "crates.io deployment"
    os: linux
    rust: stable
    stage: deploy
    env: CACHE_NAME=DEPLOY
    script: skip
    deploy:
      provider: cargo
      token: $CARGO_TOKEN
      on:
        repo: Razican/bittrex-rs
        tags: true

matrix:
  allow_failures:
  - os: windows
  - rust: nightly

# Run the multiple tests.
script:
- ./travis-helper.sh fmt_check
- ./travis-helper.sh clippy_check
- ./travis-helper.sh test

# Upload code coverage report
after_success:
- ./travis-helper.sh upload_code_coverage
