[package]
name = "bittrex"
version = "0.1.1"
authors = [
  "Razican <razican@protonmail.ch>"
]
license = "MIT/Apache-2.0"
repository = "https://github.com/Razican/bittrex-rs"
homepage = "https://bittrex.com/"
documentation = "https://docs.rs/bittrex/"
description = """\
Bittrex API bindings for Rust.
"""
readme = "README.md"
keywords = ["bittrex", "bitcoin", "API", "exchange"]

[badges]
travis-ci = { repository = "Razican/bittrex-rs", branch = "master" }
codecov = { repository = "OpenStratos/server-rs", branch = "master", service = "github" }
is-it-maintained-issue-resolution = { repository = "OpenStratos/server-rs" }
is-it-maintained-open-issues = { repository = "OpenStratos/server-rs" }

[dependencies]
lazy_static = "0.2.8"
error-chain = "0.10.0"
reqwest = "0.7.2"
sha2 = "0.6.0"
hmac = "0.4.2"
serde = "1.0.11"
serde_derive = "1.0.11"
hex = "0.2.0"

[dependencies.chrono]
version = "0.4.0"
features = ["serde"]

[dev-dependencies]
dotenv = "0.10.1"
