[package]
name = "bittrex"
version = "0.1.0"
authors = ["Razican <razican@protonmail.ch>"]

[dependencies]
lazy_static = "0.2.8"
error-chain = "0.10.0"
reqwest = "0.7.2"
sha2 = "0.6.0"
hmac = "0.4.2"
serde = "1.0.11"
serde_derive = "1.0.11"
hex = "0.2.0"

[dependencies.chrono]
version = "0.4.0"
features = ["serde"]
